---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: "{% liquid \r\n\r\nassign index = trmnl.system.timestamp_utc | modulo: 3500 | plus: 0\r\n%}\r\nhttps://raw.githubusercontent.com/ExcuseMi/trmnl-word-search-plugin/main/data/{{size}}/{{difficulty}}/{{index}}.json\r\n\r\nhttps://raw.githubusercontent.com/ExcuseMi/trmnl-word-search-plugin/main/data/8/{{difficulty}}/{{index}}.json"
polling_headers: ''
polling_body: ''
id: 189996
custom_fields:
- keyname: about
  name: About This Plugin
  field_type: author_bio
  description: Solve <strong>Word Search</strong>es directly on your TRMNL!<br /><br /> Get stuck on a tricky word search puzzle?<br />Simply scan the QR code to reveal the solution!
  github_url: https://github.com/ExcuseMi/trmnl-word-search-plugin
  category: games
- keyname: difficulty
  field_type: select
  name: Difficulty
  description: 'Difficulty levels:<br /><strong>Easy</strong>: Fewer words, only forward directions (right/down)<br /><strong>Medium</strong>: More words, 4 directions (no backwards)<br /><strong>Hard</strong>: Most words, all 8 directions'
  options:
  - Easy — Fewer words, only forward directions (right/down): easy
  - Medium  — More words, 4 directions (no backwards): medium
  - Hard — Most words, all 8 directions: hard
  default: medium
  optional: true
- keyname: size
  field_type: select
  name: Size
  description: Size of the grid<br />On smaller views, an 8x8 puzzle will be shown on small to medium screens to ensure readability.
  options:
  - 8X8: '8'
  - 10x10: '10'
  - 12x12: '12'
  - 15x15: '15'
  default: '10'
  optional: true
- keyname: show_solution
  field_type: select
  name: Show solution QR Code
  options:
  - 'Yes': 'yes'
  - 'No': 'no'
  default: 'yes'
  optional: true
name: Word Search
refresh_interval: 30
